### ISSUE TITLE
please update pore_surface

### ISSUE THREAD

**Issue by ltalirz** [pdlotko/topological_pipelines_for_porous_materials#4]
Could you please incorporate the latest updates in the `pore_surface.cpp` script as well?
This will be used by aiida.

By the way, I think it would be helpful to keep the .cpp files as short as possible and move 
some of the code related to the different subsampling procedures in to the .h files
https://github.com/pdlotko/topological_pipelines_for_porous_materials/blob/65bc0bdcc8f5385a3e8c808cff2b430dc34ea01a/subsample_pore_surface.cpp#L78-L121
This way, we can have different combinations of binaries side by side without duplicating too much code.

P.S. To keep the same indentation level, you could use
```
if () {
} else if () {
} else {
}
```

**Comment by pdlotko** [comment]
Done for both.

**Comment by ltalirz** [comment]
thanks for the quick fix, please push :-)

**Comment by pdlotko** [comment]
pushing as requested

2018-05-24 14:31 GMT+02:00 Leopold Talirz <notifications@github.com>:
